version: 2

jobs:
  test:
    docker:
      - image: cimg/node:17.9.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: package install process
          command: yarn
      - run:
          name: yarn test
          command: yarn test

workflows:
  version: 2
  example_workflows:
    jobs:
      - test